name: Health Check

on:
  schedule:
    - cron: '0 6 1 1,4,7,10 *' # runs at 6am daily

jobs:
  check_health:
    runs-on: ubuntu-latest  # Use the latest Ubuntu image

    steps:
      # Step 1: Check the deployed service URL
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
            node-version: '20'
      - name: Check the deployed service URL
        uses: jtalk/url-health-check-action@v4
        with:
          url: https://github.com/RaGuL2k23/CI-CD-Pipeline  # URL to check
          follow-redirect: false  # Optional, defaults to "false"
          max-attempts: 3  # Optional, defaults to 1
          retry-delay: 5s  # Optional, delay between retries
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}   

      # Step 2: Notify Discord on Success
      - name: Set up context
        run: |
          echo "JOB_NAME=${{ github.workflow }}" >> $GITHUB_ENV
          echo "COMMIT_HASH=${{ github.sha }}" >> $GITHUB_ENV
          echo "COMMIT_AUTHOR=${{ github.actor }}" >> $GITHUB_ENV

      - name: Test Success
        uses: rjstone/discord-webhook-notify@v1
        if: success()
        with:
          severity: info
          details: |
            Job: ${{ env.JOB_NAME }}
            Commit: ${{ env.COMMIT_HASH }}
            Author: ${{ env.COMMIT_AUTHOR }}
            Status: Test Succeeded!
          webhookUrl: "https://discord.com/api/webhooks/1258806904440754176/B45UKZleTK5b5d7DSS7SGqM67M312kr6cbgvpOVB9eOmHh2v2SzcULu0vKvDl0q_DMlq"

      - name: Test Failure
        uses: rjstone/discord-webhook-notify@v1
        if: failure()
        with:
          severity: error
          details: |
            Job: ${{ env.JOB_NAME }}
            Commit: ${{ env.COMMIT_HASH }}
            Author: ${{ env.COMMIT_AUTHOR }}
            Status: Test Failed!
          webhookUrl: "https://discord.com/api/webhooks/1258806904440754176/B45UKZleTK5b5d7DSS7SGqM67M312kr6cbgvpOVB9eOmHh2v2SzcULu0vKvDl0q_DMlq"

      - name: Test Cancelled
        uses: rjstone/discord-webhook-notify@v1
        if: cancelled()
        with:
          severity: warn
          details: |
            Job: ${{ env.JOB_NAME }}
            Commit: ${{ env.COMMIT_HASH }}
            Author: ${{ env.COMMIT_AUTHOR }}
            Status: Test Cancelled!
          webhookUrl: "https://discord.com/api/webhooks/1258806904440754176/B45UKZleTK5b5d7DSS7SGqM67M312kr6cbgvpOVB9eOmHh2v2SzcULu0vKvDl0q_DMlq"
