name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:

  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
            node-version: '20'
      - name: Install dependencies
        run: npm ci
      - name: Check style 
        run : npm run eslint 
      - name: Build check
        run : npm run build 
      - name: Test check
        run: npm run test
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Start application
        run: npm start &
      - name: Wait for server to be ready
        run: npx wait-on http://localhost:8080
      - name: Run Playwright tests
        run: npm run test:e2e
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30   
      - name: Render Deployment
      # only deploy on push and merge not on pull
        if: ${{ github.event_name == 'push' }}
        run: curl https://api.render.com/deploy/srv-${{ secrets.RENDER_SERVICE_ID }}?key=${{ secrets.RENDER_API_KEY }}
  tag_release:
          needs: [simple_deployment_pipeline]
          runs-on: ubuntu-20.04
          steps:
           - name: Get commit messages
             id: get_commit_messages
             run: |
               COMMIT_MESSAGES=$(echo '${{ toJson(github.event.commits.*.message) }}' | jq -r '. | join(" ")')
               echo "COMMIT_MESSAGES=$COMMIT_MESSAGES" >> $GITHUB_ENV
         
           - name: Print commit messages
             run: echo "$COMMIT_MESSAGES"
         
           - name: Skip tag found
             if: contains(env.COMMIT_MESSAGES, '#skip')
             run: echo "Skipping version bump"
         
           - name: Bump version and push tag
             uses: anothrNick/github-tag-action@1.36.0
             env:
               GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
               DEFAULT_BUMP: patch
               DRY_RUN: true
               RELEASE_BRANCHES: main
   
